apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubectl
  name: kubectl-pod
spec:
  serviceAccount: kubectl-admin
  containers:
  - name: kubectl
    image: ysakashita/kubectl:debug
    command:
    - sleep
    - infinity
