name: CI

on: 
  push:
    tags: ["v**"]

jobs:
  build-push:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code 
      uses: actions/checkout@v2
      with:
        fetch-edpth: 1
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v3
      with: 
        image: ysakashita/kubectl
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
